[versions]
activity-compose = "1.8.1"
android-gradle-plugin = "8.2.0"
android-test-plugin = "8.2.0"
benchmark-macro-junit4 = "1.2.2"
coil-compose = "2.5.0"
compose-bom = "2023.10.01"
compose-for-tv = "1.0.0-alpha10"
compose-ui = "1.6.0-beta02"
material3 = "1.2.0-alpha12"
core-ktx = "1.12.0"
core-splashscreen = "1.0.1"
gson = "2.9.1"
hilt-navigation-compose = "1.1.0"
hilt-android = "2.48.1"
junit = "1.1.5"
kotlin-android = "1.9.0"
kotlinx-serialization = "1.6.0"
lifecycle-runtime-ktx = "2.6.2"
media3-ui = "1.2.0"
media3-exoplayer = "1.2.0"
navigation-compose = "2.7.5"
profileinstaller = "1.3.1"
uiautomator = "2.2.0"
ui-tooling = "1.5.4"

#[versions]
#activity-compose = "1.8.1"
#android-gradle-plugin = "8.2.0"
#android-test-plugin = "8.2.0"
#benchmark-macro-junit4 = "1.2.1"
#coil-compose = "2.5.0"
#compose-bom = "2023.10.01"
#compose-for-tv = "1.0.0-alpha10"
#compose-ui = "1.6.0-beta02"
#core-ktx = "1.12.0"
#core-splashscreen = "1.0.1"
#hilt-navigation-compose = "1.1.0"
#hilt-android = "2.48.1"
#junit = "1.1.5"
#kotlin-android = "1.9.0"
#kotlinx-serialization = "1.6.0"
#ksp = "1.9.0-1.0.13"
#lifecycle-runtime-ktx = "2.6.2"
#media3-ui = "1.2.0"
#media3-exoplayer = "1.2.0"
#navigation-compose = "2.7.5"
#profileinstaller = "1.3.1"
#uiautomator = "2.2.0"
#ui-tooling = "1.5.4"
#material3 = "1.2.0-alpha12"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
androidx-benchmark-macro-junit4 = { module = "androidx.benchmark:benchmark-macro-junit4", version.ref = "benchmark-macro-junit4" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
androidx-compose-ui-base = { module = "androidx.compose.ui:ui", version.ref = "compose-ui" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose-ui" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "core-splashscreen" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt-navigation-compose" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "junit" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle-runtime-ktx" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle-runtime-ktx" }
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
androidx-media3-ui = { module = "androidx.media3:media3-ui", version.ref = "media3-ui" }
androidx-media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3-exoplayer" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation-compose" }
androidx-profileinstaller = { module = "androidx.profileinstaller:profileinstaller", version.ref = "profileinstaller" }
androidx-tv-foundation = { module = "androidx.tv:tv-foundation", version.ref = "compose-for-tv" }
androidx-tv-material = { module = "androidx.tv:tv-material", version.ref = "compose-for-tv" }
androidx-uiautomator = { module = "androidx.test.uiautomator:uiautomator", version.ref = "uiautomator" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil-compose" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt-android" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt-android" }
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "ui-tooling" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin-android" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin-android" }
android-test = { id = "com.android.test", version.ref = "android-test-plugin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt-android" }

